// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFE_CHU.Models;

#nullable disable

namespace PFE_CHU.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PFE_CHU.Models.Devision", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devisions");
                });

            modelBuilder.Entity("PFE_CHU.Models.Hopitaux", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hopitaux");
                });

            modelBuilder.Entity("PFE_CHU.Models.Role", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PFE_CHU.Models.Service", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("DevisionId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DevisionId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("PFE_CHU.Models.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("DevisionId")
                        .HasColumnType("int");

                    b.Property<int?>("HopitauxId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevisionId");

                    b.HasIndex("HopitauxId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PFE_CHU.Models.Service", b =>
                {
                    b.HasOne("PFE_CHU.Models.Devision", "Devision")
                        .WithMany("Services")
                        .HasForeignKey("DevisionId");

                    b.Navigation("Devision");
                });

            modelBuilder.Entity("PFE_CHU.Models.User", b =>
                {
                    b.HasOne("PFE_CHU.Models.Devision", "Devision")
                        .WithMany("Users")
                        .HasForeignKey("DevisionId");

                    b.HasOne("PFE_CHU.Models.Hopitaux", "Hopitaux")
                        .WithMany("Users")
                        .HasForeignKey("HopitauxId");

                    b.HasOne("PFE_CHU.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("PFE_CHU.Models.Service", "Service")
                        .WithMany("Users")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Devision");

                    b.Navigation("Hopitaux");

                    b.Navigation("Role");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PFE_CHU.Models.Devision", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PFE_CHU.Models.Hopitaux", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PFE_CHU.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PFE_CHU.Models.Service", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
